### PR TITLE
Initial Files for React Install

### PR DESCRIPTION
**Pull request by RedRuby67**
Will add more files and a readme later with clear instructions for installation.

### CODE REVIEW

**Comment by bshouse** [comment]
Before we can Merge this, everything in the node_modules needs to be removed. The node_modules folder just contains things that are installed when we do the "npm install". We need only the files in GitHub that we have authored and supporting data.  You may want to add the node_modules to your [.gitignore](http://git-scm.com/docs/gitignore) 

As a purest, I would also like to see the examples and other unnecessary files removed from the react folder. However, I will flex on this point if the team so wishes. In any case, you will want to move any files that need to be passed to the web browser into the static folder (or a sub-directory thereof) so that the web server can "deliver" them. 

Please let me know if you have any questions or if there is anything I can do to assist.

Thank you.

**Comment by bshouse** [comment]
Much better. Thank you.

One more picky thing. The gitignore file is specific to each person. For instance, I do not have any *.project files. Could you also remove the gitignore from the branch and I promise to merge.

Thanks again.

**Comment by wderaad** [comment]
I have to agree, and would like to see all the examples and non-project related files removed. This way we can keep our repository a manageable size. Let me know where you'd like me to help out working on the client side of the project.

**Comment by RedRuby67** [comment]
Removed majority of examples and working on template for website.

**Comment by RedRuby67** [comment]
Hey, guys. I'm a little confused on something: so I understand that the gitignore file should be unique to each person. But how can I keep my own gitignore file unique while removing it from the branch? Do I include the gitignore in the .gitignore file or something?

**Comment by wderaad** [comment]
Yeah if you include it in your .gitignore you'll no longer see it when you check that status of your branch. Alternatively you can add each file individually that you would like to commit and untracked files will not be included in your commit.

**Comment by bshouse** [comment]
I have checked out this Pull Request and believe I have a commit that will merge it into the project.

Please let me know if there is anything I can assist with or if you would like me to add the changes to this pull request.

Thank you.

**Comment by RedRuby67** [comment]
Fork is now up to date with bshouse. I re-added the index.js file, which I guess was removed. Hope that's not a problem. Or I can just delete it again and push.

**Comment by bshouse** [comment]
The index.js is no longer needed since we use sinatra as the production Web
server.

Brett

**Comment by bshouse** [comment]
It looks good to me. Merged.

**Pull request merged**
